// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages(
    conversation_id, role, content, widgets, documents, pages, is_partial
) VALUES(
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, conversation_id, role, content, widgets, documents, pages, is_partial, created_at
`

type InsertMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	Widgets        []byte      `json:"widgets"`
	Documents      []byte      `json:"documents"`
	Pages          []byte      `json:"pages"`
	IsPartial      bool        `json:"is_partial"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Widgets,
		arg.Documents,
		arg.Pages,
		arg.IsPartial,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Widgets,
		&i.Documents,
		&i.Pages,
		&i.IsPartial,
		&i.CreatedAt,
	)
	return i, err
}

const listMessageByConversationID = `-- name: ListMessageByConversationID :many
SELECT id, conversation_id, role, content, widgets, documents, pages, is_partial, created_at 
FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessageByConversationID(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessageByConversationID, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Widgets,
			&i.Documents,
			&i.Pages,
			&i.IsPartial,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, conversation_id, role, content, widgets, documents, pages, is_partial, created_at
FROM messages
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Widgets,
			&i.Documents,
			&i.Pages,
			&i.IsPartial,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
