// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateConversation(ctx context.Context, title string) (Conversation, error)
	GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	ListConversations(ctx context.Context) ([]Conversation, error)
	ListMessageByConversationID(ctx context.Context, conversationID pgtype.UUID) ([]Message, error)
	UpdateConversationTime(ctx context.Context, id pgtype.UUID) (Conversation, error)
}

var _ Querier = (*Queries)(nil)
